services:
  - type: web
    name: laravel-app
    env: docker
    dockerfilePath: ./Dockerfile
    workingDirectory: /var/www
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: local
    volumes:
      - name: laravel-env
        mountPath: /var/www/.env
    healthCheckPath: /health

  - type: web
    name: nginx
    env: docker
    image:
      url: nginx:alpine
    ports:
      - 8000
    volumes:
      - name: laravel-src
        mountPath: /var/www
      - name: nginx-conf
        mountPath: /etc/nginx/conf.d/default.conf
    dependsOn:
      - laravel-app
      - mysql-db

  - type: web
    name: laravel-node
    env: docker
    dockerfilePath: ./Dockerfile.node
    platform: linux/arm64/v8
    ports:
      - 3000
    volumes:
      - name: laravel-src
        mountPath: /var/www
      - name: node-modules
        mountPath: /var/www/node_modules
    autoDeploy: true

  - type: pserv
    name: mysql-db
    env: docker
    image:
      url: mysql:8.0
    platform: linux/x86_64
    envVars:
      - key: MYSQL_DATABASE
        value: ${DB_DATABASE}
      - key: MYSQL_ROOT_PASSWORD
        value: ${DB_PASSWORD}
      - key: MYSQL_USER
        value: ${DB_USERNAME}
      - key: MYSQL_PASSWORD
        value: ${DB_PASSWORD}
    disk:
      name: db-data
      mountPath: /var/lib/mysql
      sizeGB: 5

