services:
  - type: web
    name: my-laravel-app
    env: docker
    build:
      dockerfilePath: Dockerfile
      context: .
    image: my-laravel-app
    containerName: my-laravel-app
    restartPolicy: unless-stopped
    workingDirectory: /var/www
    volumes:
      - ./:/var/www
      - ./.env:/var/www/.env
    environmentVariables:
      - key: APP_ENV
        value: local
    ports:
      - 8000:80
    network:
      name: app-network

  - type: web
    name: my-nginx
    env: docker
    image: nginx:alpine
    containerName: my-nginx
    ports:
      - 8000:80
    volumes:
      - ./:/var/www
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    dependsOn:
      - my-laravel-app
      - my-mysql
    network:
      name: app-network

  - type: web
    name: my-laravel-node
    env: docker
    build:
      dockerfilePath: Dockerfile.node
      context: .
    image: my-laravel-node
    containerName: my-laravel-node
    ports:
      - 3000:3000
    restartPolicy: unless-stopped
    workingDirectory: /var/www
    volumes:
      - ./:/var/www
      - /var/www/node_modules
    network:
      name: app-network

  - type: database
    name: my-mysql
    env: docker
    image: mysql:8.0
    containerName: my-mysql
    restartPolicy: unless-stopped
    environmentVariables:
      - key: MYSQL_DATABASE
        value: ${DB_DATABASE}
      - key: MYSQL_ROOT_PASSWORD
        value: ${DB_PASSWORD}
      - key: MYSQL_PASSWORD
        value: ${DB_PASSWORD}
      - key: MYSQL_USER
        value: ${DB_USERNAME}
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306
    network:
      name: app-network

networks:
  - name: app-network

volumes:
  - name: dbdata
